---
title: "Readme"
author: "Georgia P"
date: "September 10, 2015"
output: html_document
---
# Summary
The script below crunches data produced during a series of experiments with mobile device measurements performed by 30 volunteers.
The **goal** is to preprocess the data located in various files and folders and produce a tidy data set for analysis that containts per subject (volunteer#) and activity (walking, laying, sitting and variations) a seat of measurments and their mean values over the duration of the experiment.


The original data was obtained on the following site where the full descriptions can also be found
http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 
#Acknowledgements
#Dataset used is by [1] Davide Anguita, Alessandro Ghio, Luca Oneto, Xavier Parra and Jorge L. Reyes-Ortiz. Human Activity Recognition on Smartphones using a Multiclass Hardware-Friendly Support Vector Machine. 
#International Workshop of Ambient Assisted Living (IWAAL 2012). Vitoria-Gasteiz, Spain. Dec 2012


# Process
The operations performed on the data follow the following series of actions :
1. Merge of the training and the test sets to create one data set.  
2. Extraction only of the measurements on the mean and standard deviation for each measurement.   
3. Replacement of indexes of activities with their descriptive activity names to name the activities in the data set  
4. Appropriate labeling of the data set with descriptive variable names.   
5. From the data set in step 4, creation a second, independent tidy data set with the average of each variable for each activity and each subject.  



 1. Merge of the training and the test sets to create one data set.    

**READ** 
Data is read from the various sources.
    1.1 Get the names of the activities that correspond to classes by reading 'activity_labels.txt': Links the class labels with their activity name.
    1.2 Reading 'train/X_train.txt': Training set. Same for test set
    1.3 Reading 'train/y_train.txt': Training labels. Same for test set
    1.4 Read subject info for train set. Same for test set


```{r1 echo=FALSE }
 activity_labels<- fread("./UCI HAR Dataset/activity_labels.txt")
 trainset<- read.table("./UCI HAR Dataset/train/X_train.txt") ; testset<- read.table("./UCI HAR Dataset/test/X_test.txt")
 trainnames<- fread("./UCI HAR Dataset/train/y_train.txt") ; testnames<- fread("./UCI HAR Dataset/test/y_test.txt")
 subjecttrain<- fread("./UCI HAR Dataset/train/subject_train.txt") ;subjecttest<- fread("./UCI HAR Dataset/test/subject_test.txt")
```

**MERGE** 
 
 Start the merge in phases : First merge Subject info with Activity Class and Description for train sample, then for test sample, assumming they are ordered to match. No common key to join them on, other than their as-is index.
 
```{r2 echo=FALSE }
library(dplyr)
 #create indexes, preparing for join
 test_size<- length(testset[,1]) ;  train_size<- length(trainset[,1])
 
 trainset$ID <- seq(1,train_size, by=1) ; trainnames$ID<- seq(1,train_size, by=1) ; subjecttrain$ID<- seq(1,train_size, by=1)
 testset$ID <- seq(1,test_size, by=1) ; testnames$ID<- seq(1,test_size, by=1) ; subjecttest$ID<- seq(1,test_size, by=1)
 
 #rename V1 in testnames/trainnames to class to avoid merging on generic V1. Same for subjectnames
 names(testnames)[1]<-"class" ; names(trainnames)[1]<-"class"
 names(subjecttest)[1]<-"subject" ;  names(subjecttrain)[1]<-"subject"

 #create lists, for multiple merges
 trainlist <-list(trainset, trainnames, subjecttrain) ; testlist <-list(testset, testnames, subjecttest)

 #merge all based on their commony key = ID (automatically selected by join_all)
 library(plyr)
 train <- join_all(trainlist)
 test <- join_all(testlist)
 
 #Create a universal index across test and train : move index for table "test" by the size of table "train"
 test$ID<- test$ID+length(train[,1])
 #final merge/ as I want every measurement to remain on a separate row, 
 #I am building up a dataframe in which the first part is my trainset and the second part is my test set
 dataset<- train
 dataset[length(train[,1]) :(length(train[,1])+ length(test[,1])) , ]<- test
 
 #validate that everything went as planned by comparing before after sizes
 if( length(dataset[,1]) == (length(train[,1])+ length(test[,1]))) print("ok")
```
 
 
2. Extract only the measurements on the mean and standard deviation for each measurement.   
  This can be easily performed by scanning the **descriptive names** of each column of the measurement. Having noticed that the type of calculation (mean, st dev or other ) is explictly mentioned on the description, it is fairly simple to use a **regular expression** for subsetting the original vector and reduce it only to the desired mean and st dev measurements.

4. Appropriately labels the data set with descriptive variable names. 

This is a step later required, yet it will enable the process by being implemented at this phase
**RENAME & FILTER WITH REGEX**
```{r3 echo=FALSE }
#Get the measurements names by reading the 'features.txt': List of all features.
feature_names <-fread("./UCI HAR Dataset/features.txt")
# 4. Appropriately labels the data set with descriptive variable names. 
#rename my dataset features with their names as mentioned in the features.txt
names(dataset)[1:561] <-feature_names$V2
#apply Regular Expression for names that contain either "mean" or Mean or "std"
index<-grep("[Mm]ean|std", names(dataset))
#subset my dataset keeping only the desired, values
sub_set<-dataset[,index] ; sub_set$ID <- dataset$ID; sub_set$class <- dataset$class; sub_set$subject <- dataset$subject
```
            
3. Use descriptive activity names to name the activities in the data set 
  I already have the activity classes in my dataset. All I have to do is match them with their description using a join.

```{r4 echo=FALSE }
# Get the names of the activities that correspond to classes by reading 'activity_labels.txt': Links the class labels with their activity name.
activity_labels<- fread("./UCI HAR Dataset/activity_labels.txt")
names(activity_labels)<-c("class", "activity_description")

#Well I have 2 data sets so I will merge them both with the activity_labels
dsc_dataset<-left_join(dataset,activity_labels)
dsc_subset<-left_join(sub_set,activity_labels)
```

5. From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject. 
This is a process that can be operated using the dplyr package and more specifically group_by and summarize by mean. To make this work I am making some interim clean-ups, new variables and then re-trasnforming my data to ge them in a **tidy** status. While in the original experiment each measurement was represented by a vector containing all possible measurement types, I have chosen to build my tidy data with 4 columns :
 1. Subject #
 2. Activity performed
 3. Measurement Category 
 4. Mean value over the experiment duration.
 
 Data is exported to a txt file.


```{r5 echo=FALSE }
# Create a new key that identifies Activity per Subject
tidy<- dsc_subset
tidy$Subject_Activity <- paste(tidy$subject,"-", tidy$activity_description)
#cleanup to keep only numerical values
subm<- tidy[, 1:87]
# rebuild by adding Subject Activity information
subm$SA<-tidy$Subject_Activity
subject_monitor<- group_by(subm, SA) %>% summarise_each(funs(mean))

# export data
write.table(dataset, "tidy_dataset.txt", row.name=FALSE)
```


